com.instana.plugin.ebpf:
  enabled: false
# com.instana.plugin.process:
#   processes:
#     - 'node'
# com.instana.plugin.nodejs:
#   span-batching-enabled: true

# Esempio stile OpenTelemetry Collector
# receivers:
#   otlp:
#     protocols:
#       grpc:
#         endpoint: 0.0.0.0:4317
#       http:
#         endpoint: 0.0.0.0:4318
com.instana.plugin.opentelemetry:
  enabled: false
# Java Tracing
# https://www.ibm.com/docs/en/iofgs?topic=references-configuration-based-java-trace-sdk
com.instana.plugin.javatrace:
  instrumentation:
    sdk:
      targets:
        - match:
            type: class
            name: com.example.App
            method: main
          span:
            name: Job
            type: ENTRY
            stackDepth: 20
            tags:
              - kind: constant
                name: endpoint
                value: BatchJob
              - kind: argument
                name: batch.job
                index: 0
        - match:
            type: class
            name: com.example.App
            method: insertCurrent
          span:
            name: DatabaseCall
            type: EXIT
            stackDepth: 2
            tags:
              - kind: constant
                name: db.connection_string
                value: jdbc:postgresql://localhost:5432/demo
              - kind: argument
                name: db.statement
                index: 0