services:
  db:
    image: postgres:16-alpine
    container_name: pg-db
    pid: "container:collector"
    networks: "container:collector"
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    # ports:
    #   - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:Z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build: ./app
    depends_on:
      db:
        condition: service_healthy
      # jaeger:
      #   condition: service_started
      # instana-agent:
      #   condition: service_started
    container_name: app
    network_mode: "container:collector"
    pid: "container:collector"
    environment:
      # --- DB & app settings (immutati) ---
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: demo
      DB_USER: demo
      DB_PASSWORD: demo
      CITIES: "Milan,Paris,Berlin,New York,Tokyo"
      PAST_DAYS: "1"
      TIMEZONE: "Europe/Rome"
      POLL_SECONDS: "5"

# --- OpenTelemetry: invia direttamente a Jaeger all-in-one via OTLP gRPC ---
      OTEL_SERVICE_NAME: "michele"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://localhost:4317"   # gRPC default 4317
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"

# In alternativa HTTP/protobuf:
# OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
# OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://jaeger:4318/v1/traces"

# https://opentelemetry.io/docs/zero-code/java/agent/getting-started/
# Aggiunge il Java agent OpenTelemetry al comando di avvio dell'app Java

    entrypoint:
      - "java"
      - "-javaagent:/opt/app/opentelemetry-javaagent.jar"
      - "-Dotel.service.name=michele"
      - "-jar"
      - "/opt/app/app.jar"
# ports:
#   - "4317:4317"   # (solo se vuoi esporre dall'app; non necessario per Jaeger)
#   - "4318:4318"
  # jaeger:
  #   profiles:
  #     - jaeger
  #   image: cr.jaegertracing.io/jaegertracing/jaeger:2.14.0
  #   container_name: collector
  #   ports:
  #     - "16686:16686"  # UI
  #     - "4317:4317"    # OTLP gRPC ingest
  #     - "4318:4318"    # OTLP HTTP ingest
  #     # porte aggiuntive (Zipkin, agent) se ti servono:
  #     # - "5778:5778"
  #     # - "9411:9411"

    # All-in-one usa storage in-memory per demo

  instana-agent:
    # profiles:
    #   - agent
    image: icr.io/instana/agent
    # network_mode: "container:app"
    # pid: "container:app"
    container_name: collector
    hostname: michele
    environment:
      - INSTANA_AGENT_ENDPOINT=ingress-orange-saas.instana.io
      - INSTANA_AGENT_ENDPOINT_PORT=443
      - INSTANA_AGENT_KEY=xxxxxxxxxxx
      - INSTANA_DOWNLOAD_KEY=xxxxxxxxxxx
      - INSTANA_AUTO_PROFILE=true
    volumes:
      - ./configuration.custom.yaml:/opt/instana/agent/etc/instana/configuration.custom.yaml:Z
      - ./custom.cfg:/opt/instana/agent/etc/instana/custom.cfg:Z
